name: Deploy to GitHub Pages

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "src/"  # Ajusta esto según tu estructura real

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
