name: Deploy to GitHub Pages

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Crear el directorio src si no existe
      run: mkdir -p src/

    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      with:
        name: artefacto
        path: src/ # Ruta ajustada para subir el contenido del directorio src/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
