name: Deploy to GitHub Pages

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Crear y verificar directorio src
      run: |
        mkdir -p src/
        touch src/archivo-prueba.txt
        echo "Directorio src creado."

    - name: Listar contenido del directorio src
      run: ls -la src/

    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      with:
        name: artefacto
        path: src/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
