name: Desplegar en GitHub Pages
on:
  push:
    branches: [main, develop]  # Se activa al hacer push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Desplegar
        run: echo "¡Sitio desplegado!"  # Reemplaza esto con tus pasos de despliegue
