name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587                  
        username: ${{ secrets.EMAIL_USERNAME }}  # Nombre de usuario de tu correo
        password: ${{ secrets.EMAIL_PASSWORD }}  # Contraseña de tu correo
        subject: 'Nuevo Commit en el Repositorio'
        body: 'Se ha realizado un nuevo commit en la rama main.'
        to: 'dhangy.jp@gmail.com'      # Cambia esto por el correo del destinatario
        from: 'josepalaciososcata17@gmail.com'       # Cambia esto por tu correo
